### ISSUE TITLE
مشکل صفحه سفید

### ISSUE THREAD

**Issue by XShaan** [amir-sheikhzadeh/PayPing-in-PHP#1]
سلام ، بعد از پر کردن فرم به صفحه
 pay.php
 میره اما صفحه سفید میشه و هیچ اتفاقی دیگه نمیوفته !
توکن و ادرس سایت هم وارد شده و ...

ضمناً بنده 
$header['http_code']
echo کردم اررور 401 برگشت داد در صورتی که بنده تمام موارد رو درست وارد کردم ! توکن و ...

**Comment by amir-sheikhzadeh** [comment]
سلام اگه  در فایل
 pay.php
توکن رو وارد کرده باشید باید بدون مشکل کار کنه  مگر اینکه توکنی که وارد کردید مشکل داشته باشه با پشتبانی پی پینگ بخش فنی تماس بگیرید بگید توکنتون رو بررسی کنند
 کدهای پی پینگ : 

200	عملیات با موفقیت انجام شد
400	مشکلی در ارسال درخواست وجود دارد
500	مشکلی در سرور رخ داده است
503	سرور در حال حاضر قادر به پاسخگویی نمی‌باشد
401	عدم دسترسی
403	دسترسی غیر مجاز
404	آیتم درخواستی مورد نظر موجود نمی‌باشد


اگر از توکن تستی استفاده می کنید باید توکنتون این دسترسی ها رو داشته باشه
openid
profile
email
pay:write

**Comment by XShaan** [comment]
تشکر مشکل عدم دسترسی بود که حل شد ممنون
